export const MAX_DATA_POINTS = 100;

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'he', name: 'עברית' },
];

export const translations: { [key: string]: { [key: string]: string } } = {
  en: {
    appTitle: 'dB Decibel Meter Live',
    settings: 'Settings',
    readyToMeasure: 'Ready to measure sound?',
    permissionPrompt: "Click the button below to start the decibel meter. You'll need to grant microphone access when prompted.",
    startMeter: 'Start Meter',
    stopMeter: 'Stop Meter',
    soundLevel: 'Sound Level',
    average: 'Average',
    max: 'Max',
    liveSoundLevel: 'Live Sound Level',
    theme: 'Theme',
    bright: 'Bright',
    dark: 'Dark',
    language: 'Language',
    about: 'About',
  },
  es: {
    appTitle: 'Medidor de Decibelios dB en Vivo',
    settings: 'Ajustes',
    readyToMeasure: '¿Listo para medir el sonido?',
    permissionPrompt: 'Haga clic en el botón de abajo para iniciar el medidor de decibelios. Deberá conceder acceso al micrófono cuando se le solicite.',
    startMeter: 'Iniciar Medidor',
    stopMeter: 'Detener Medidor',
    soundLevel: 'Nivel de Sonido',
    average: 'Promedio',
    max: 'Máx',
    liveSoundLevel: 'Nivel de Sonido en Vivo',
    theme: 'Tema',
    bright: 'Claro',
    dark: 'Oscuro',
    language: 'Idioma',
    about: 'Acerca de',
  },
  fr: {
    appTitle: 'Sonomètre dB en Direct',
    settings: 'Paramètres',
    readyToMeasure: 'Prêt à mesurer le son ?',
    permissionPrompt: "Cliquez sur le bouton ci-dessous pour démarrer le sonomètre. Vous devrez autoriser l'accès au microphone lorsque vous y êtes invité.",
    startMeter: 'Démarrer le Sonomètre',
    stopMeter: 'Arrêter le Sonomètre',
    soundLevel: 'Niveau Sonore',
    average: 'Moyenne',
    max: 'Max',
    liveSoundLevel: 'Niveau Sonore en Direct',
    theme: 'Thème',
    bright: 'Clair',
    dark: 'Sombre',
    language: 'Langue',
    about: 'À propos',
  },
  de: {
    appTitle: 'dB Schallpegelmesser Live',
    settings: 'Einstellungen',
    readyToMeasure: 'Bereit zur Schallmessung?',
    permissionPrompt: 'Klicken Sie auf die Schaltfläche unten, um den Dezibel-Messer zu starten. Sie müssen den Mikrofonzugriff erlauben, wenn Sie dazu aufgefordert werden.',
    startMeter: 'Messer starten',
    stopMeter: 'Messer stoppen',
    soundLevel: 'Schallpegel',
    average: 'Durchschnitt',
    max: 'Max',
    liveSoundLevel: 'Live-Schallpegel',
    theme: 'Thema',
    bright: 'Hell',
    dark: 'Dunkel',
    language: 'Sprache',
    about: 'Über',
  },
  he: {
    appTitle: 'מד דציבלים dB חי',
    settings: 'הגדרות',
    readyToMeasure: 'מוכן למדוד רעש?',
    permissionPrompt: 'לחץ על הכפתור למטה כדי להפעיל את מד הדציבלים. תצטרך לאשר גישה למיקרופון כשתתבקש.',
    startMeter: 'הפעל מד',
    stopMeter: 'עצור מד',
    soundLevel: 'עוצמת רעש',
    average: 'ממוצע',
    max: 'מקסימום',
    liveSoundLevel: 'עוצמת רעש חיה',
    theme: 'ערכת נושא',
    bright: 'בהיר',
    dark: 'כהה',
    language: 'שפה',
    about: 'אודות',
  },
};